### ISSUE TITLE
feat(ui): create reusable fetch client

### ISSUE THREAD

**Issue by dev-bre** [switchfeat-com/switchfeat#11]
The current http calls that the React app sends to the server are pretty much a copy and paste. Would be nice to have a centralized http client which all components would use to send reaquests to the backend.

**Comment by ryouaki** [comment]
means need a feature to control the http request base on axios?

**Comment by dev-bre** [comment]
It means having a centralized place in the UI project,  to execute all the fetch calls which will include common headers, config, etc. If you look at the code, the fetch calls are spread across multiple components and repeating the same code over and over.

Let's use Fetch instead of Axios please.

**Comment by dev-bre** [comment]
@ryouaki would you like to work on this? I can assign this task to you if you want.
