### ISSUE TITLE
feat(ui): add notifications

### ISSUE THREAD

**Issue by dev-bre** [switchfeat-com/switchfeat#2]
As a developer I would like to use a generic notification system which can be used in multiple  places in the UI. 

Every time the user execute an action, like create a flag, delete, update etc a notification should show up to either confirm success or show an error. 

All pages should share the same approach to showing notifications. Might be good to have a notification provider or something.

**Comment by dev-bre** [comment]
You are totally right. I updated the description with some context.if you have questions just shout.

I see there is PR already which has a notification system in it, but that PR is not going to be merged since it is not enough focused on the issue. Might be worth looking at it maybe as well.

**Comment by Zeeshnhmd** [comment]
ok so in that case how about using Toastify.js https://github.com/apvarun/toastify-js/blob/master/README.md

**Comment by dev-bre** [comment]
I have used this: [https://react-hot-toast.com/](https://react-hot-toast.com/) in the past which works perfectly with React. 

I would rather have this on, if that works for you.

**Comment by dev-bre** [comment]
Cool.

1. Yes please all changes related to the react app should go in there 
2. Sounds great!

3.  I am using Tailwind which is a phenomenal UI library. I would like to keep it without adding more libraries into the mix.

Thanks!

**Comment by dev-bre** [comment]
@Zeeshnhmd do you have any plans on when you can work on this?

**Comment by Zeeshnhmd** [comment]
Hey, @dev-bre raised a PR please have a look and let me know if you need any changes.

Thank you.

**Comment by dev-bre** [comment]
@Zeeshnhmd here it is how I modified your provider to support Tailwind styled content. https://github.com/switchfeat-com/switchfeat/pull/39 . Thanks for your PR, it open the way to this customization.
