### ISSUE TITLE
feat(api): create sdk routes for get requests

### ISSUE THREAD

**Issue by dev-bre** [switchfeat-com/switchfeat#20]
The SDK is going to use a dedicated set of routes mainly around reading the state of a flag. 
The SDK can only read data and not change the datastore.

Possible endpoints:

- evaluate-flag (this is half done already) 
- get-flags 
- get-segments
- get-conditions-by-segment
- get-rules-by-flag

**Comment by lazyfuhrer** [comment]
Hey, I'd like to work on this. Assign me @dev-bre

**Comment by dev-bre** [comment]
Thanks a lot @lazyfuhrer. I already have some work on this, but it is not complete. I can merge my stuff and let you continue on it. Sounds good?

**Comment by lazyfuhrer** [comment]
Yeah sure!

**Comment by dev-bre** [comment]
Give me an hour and I will push my stuff.

**Comment by dev-bre** [comment]
@lazyfuhrer the foundation of the sdk api endpoint is in main branch. I also updated the issue description with some potential endpoints would be nice to have. Feel free to fork and go! any issue let me know.

**Comment by lazyfuhrer** [comment]
Alright!

**Comment by dev-bre** [comment]
@lazyfuhrer do you have any plan when you would start working on this?

**Comment by lazyfuhrer** [comment]
Will start working today on this

**Comment by dev-bre** [comment]
This is great! 💪

**Comment by lazyfuhrer** [comment]
Is the function for getting all the segments already implemented or do I have to create it ?

**Comment by dev-bre** [comment]
Hey, if you look at the segmentsService, you will find functions to access the segments already. 

The API used by the UI gets the segments like this:

https://github.com/switchfeat-com/switchfeat/blob/7bbe373a1b282f273215eceb5ca89232f5cd6403/packages/api/src/routes/segmentsRoutes.ts#L19

**Comment by lazyfuhrer** [comment]
yup got it

**Comment by lazyfuhrer** [comment]
Review #37

**Comment by dev-bre** [comment]
Thanks for the PR. looks good so far. Would like to work on:
- get-conditions-by-segment
- get-rules-by-flag
As well as part of this PR?

**Comment by lazyfuhrer** [comment]
Sure. Can you tell me where is the implementation of these services ?

**Comment by dev-bre** [comment]
For get-conditiiins-by-segment
You need to create a new function in the segmentService which given a segment key, returns the list of conditions. Pretty simple, conditions is a property of a single segment. Once you have the service function, you can expose it in an sdk API endpoint.

Same idea for the rules by flag. In the flagService add a function that given a flag key, returns the list of related rules.

**Comment by lazyfuhrer** [comment]
Cool

**Comment by lazyfuhrer** [comment]
![build-fail](https://github.com/switchfeat-com/switchfeat/assets/64888892/fecbd7a7-5db4-4f3e-a25f-56892a2a6dc8)
My build got failed after fetching from the latest upstream. check this. maybe some issue at switchfeat/ui

**Comment by dev-bre** [comment]
what's the error?

**Comment by lazyfuhrer** [comment]
yup fixed now. thanks

**Comment by lazyfuhrer** [comment]
now check #37
