### ISSUE TITLE
bug(ui): login - 'view documentation' button broken link

### ISSUE THREAD

**Issue by acollazog11** [switchfeat-com/switchfeat#47]

**Comment by dev-bre** [comment]
Thanks a lot for raising this @acollazog11 would like to work on it yourself?

**Comment by acollazog11** [comment]
Sure, happy to contribute.
Should it point to [https://docs.switchfeat.com](https://docs.switchfeat.com) right?

**Comment by dev-bre** [comment]
Great!

That's correct. There might other places which are supposed to point to docs. If you could take a look around would be super cool.

Thanks!

**Comment by acollazog11** [comment]
will take a look, thanks for confirming!

**Comment by acollazog11** [comment]
it is in the "Login" component, the View Documentation link

![Screenshot 2023-07-26 at 16 57 12](https://github.com/switchfeat-com/switchfeat/assets/16126431/299811f8-7516-4c69-a238-f4bad19128eb)

**Comment by dev-bre** [comment]
well spotted! that clarifies. I updated the issue title as well. thanks!

**Comment by acollazog11** [comment]
Hey @dev-bre, can you give me permission to push a new branch and create the PR?

**Comment by dev-bre** [comment]
This has been addressed in #51
